### ISSUE TITLE
Update D3-voronoi-map dependency 

### ISSUE THREAD

**Issue by Vinay1612** [Kcnarf/d3-voronoi-treemap#12]
The D3-voronoi-map dependency in this project is not the updated version which has bug fixes.

**Comment by Kcnarf** [comment]
Package.json defines `"d3-voronoi-map": ">=1.2.0 1.*"`, meaning it requires a version >1.2 and <2. This is because v2.* of d3-voronoi-map has new APIs.

**Comment by Kcnarf** [comment]
d3-voronoi-treemap v1.1.1 no uses d3-voronoi-map v2
