### ISSUE TITLE
Request support for the vite environment

### ISSUE THREAD

**Issue by haoshuai999** [Kcnarf/d3-voronoi-treemap#18]
Recently, Svelte started to use the latest version of vite to for new projects. Vite doesn't support the current way of importing functions in the "src/d3-voronoi-treemap.js". I found out that way to make the package works again is to replace the first line of "src/d3-voronoi-treemap.js" to `import * as voronoiMap from 'd3-voronoi-map'`. Could the development team of d3-voronoi-map considering changing the file to make it compatible to vite environment? Thank you!

**Comment by Kcnarf** [comment]
Hi, 
I will take a look today at your issue and proposal.
