### ISSUE TITLE
d3VoronoiMap.voronoiMap is not a function

### ISSUE THREAD

**Issue by Itopian** [Kcnarf/d3-voronoi-treemap#9]
Greetings,

Receiving the subject error from the below code:

```
var stratify = d3.stratify()
            .id(function(d) { return d.id_field; })
            .parentId(function(d) { return d.parent_field; });

let tree = stratify(data);

function weightAccessor(d) {
            return d.value_field;
}

var rootNode = d3.hierarchy(tree, d => d.values); 

rootNode.sum(weightAccessor);

var voronoiTreemap = d3.voronoiTreemap().clip([[0, 0], [0, h], [w, h], [w, 0]]);
voronoiTreemap(rootNode);
```

Using all the latest versions of the libs and loading in the correct order:

<script type="text/javascript" src="../libs/vendor/d3-weighted-voronoi.js"></script>
<script type="text/javascript" src="../libs/vendor/d3-voronoi-map.js"></script>
<script type="text/javascript" src="../libs/vendor/d3-voronoi-treemap.js"></script>

FYI - using d3 v5

Any advice for correcting the error?

Thanks and Great Work!

**Comment by Kcnarf** [comment]
Hi,
as stated in [readme/installing](https://github.com/Kcnarf/d3-voronoi-treemap#installing), the latest d3-voronoi-treemap (v1.1.0 when writing this message) requires d3-voronoi-map v.1.2.0, which is NOT the latest one.

If you use NPM, this is not the problem. In vanilla JS, if you import script on your own via <script> tags (as it seems to be), then it may explain the issue your facing.

**Comment by Kcnarf** [comment]
6 months without further interactions ...
